FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit pandas sqlalchemy psycopg2-binary pyyaml altair

COPY src/ /app/src/
COPY configs/ /app/configs/

ENV PYTHONPATH=/app
ENV RULES_PATH=/app/configs/rules.yaml
ENV RULES_JSON_PATH=/app/configs/rules.json
ENV CONFIGS_DIR=/app/configs
EXPOSE 8501

CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
